// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: file_meta.proto

package metadata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Agreement_AgreementStatus int32

const (
	Agreement_INIT      Agreement_AgreementStatus = 0
	Agreement_COMPLETED Agreement_AgreementStatus = 1
)

var Agreement_AgreementStatus_name = map[int32]string{
	0: "INIT",
	1: "COMPLETED",
}

var Agreement_AgreementStatus_value = map[string]int32{
	"INIT":      0,
	"COMPLETED": 1,
}

func (x Agreement_AgreementStatus) String() string {
	return proto.EnumName(Agreement_AgreementStatus_name, int32(x))
}

func (Agreement_AgreementStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b47804ec1b8d60b, []int{1, 0}
}

type AgreementMeta struct {
	AgreementId          string   `protobuf:"bytes,1,opt,name=agreement_id,json=agreementId,proto3" json:"agreement_id,omitempty"`
	SpId                 string   `protobuf:"bytes,2,opt,name=sp_id,json=spId,proto3" json:"sp_id,omitempty"`
	CreatorId            string   `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ShardHash            string   `protobuf:"bytes,4,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`
	ShardIndex           uint64   `protobuf:"varint,5,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	ShardSize            uint64   `protobuf:"varint,6,opt,name=shard_size,json=shardSize,proto3" json:"shard_size,omitempty"`
	Price                uint64   `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Amount               uint64   `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Token                string   `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	AutoRenewal          bool     `protobuf:"varint,10,opt,name=auto_renewal,json=autoRenewal,proto3" json:"auto_renewal,omitempty"`
	StorageStart         uint64   `protobuf:"varint,11,opt,name=storage_start,json=storageStart,proto3" json:"storage_start,omitempty"`
	StorageEnd           uint64   `protobuf:"varint,12,opt,name=storage_end,json=storageEnd,proto3" json:"storage_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgreementMeta) Reset()         { *m = AgreementMeta{} }
func (m *AgreementMeta) String() string { return proto.CompactTextString(m) }
func (*AgreementMeta) ProtoMessage()    {}
func (*AgreementMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b47804ec1b8d60b, []int{0}
}
func (m *AgreementMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AgreementMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AgreementMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AgreementMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgreementMeta.Merge(m, src)
}
func (m *AgreementMeta) XXX_Size() int {
	return m.Size()
}
func (m *AgreementMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AgreementMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AgreementMeta proto.InternalMessageInfo

func (m *AgreementMeta) GetAgreementId() string {
	if m != nil {
		return m.AgreementId
	}
	return ""
}

func (m *AgreementMeta) GetSpId() string {
	if m != nil {
		return m.SpId
	}
	return ""
}

func (m *AgreementMeta) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *AgreementMeta) GetShardHash() string {
	if m != nil {
		return m.ShardHash
	}
	return ""
}

func (m *AgreementMeta) GetShardIndex() uint64 {
	if m != nil {
		return m.ShardIndex
	}
	return 0
}

func (m *AgreementMeta) GetShardSize() uint64 {
	if m != nil {
		return m.ShardSize
	}
	return 0
}

func (m *AgreementMeta) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AgreementMeta) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AgreementMeta) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AgreementMeta) GetAutoRenewal() bool {
	if m != nil {
		return m.AutoRenewal
	}
	return false
}

func (m *AgreementMeta) GetStorageStart() uint64 {
	if m != nil {
		return m.StorageStart
	}
	return 0
}

func (m *AgreementMeta) GetStorageEnd() uint64 {
	if m != nil {
		return m.StorageEnd
	}
	return 0
}

type Agreement struct {
	Meta                 *AgreementMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SpSignature          []byte                    `protobuf:"bytes,2,opt,name=sp_signature,json=spSignature,proto3" json:"sp_signature,omitempty"`
	CreatorSignature     []byte                    `protobuf:"bytes,3,opt,name=creator_signature,json=creatorSignature,proto3" json:"creator_signature,omitempty"`
	CreateTime           uint64                    `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Status               Agreement_AgreementStatus `protobuf:"varint,5,opt,name=status,proto3,enum=filemeta.Agreement_AgreementStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Agreement) Reset()         { *m = Agreement{} }
func (m *Agreement) String() string { return proto.CompactTextString(m) }
func (*Agreement) ProtoMessage()    {}
func (*Agreement) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b47804ec1b8d60b, []int{1}
}
func (m *Agreement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Agreement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Agreement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Agreement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agreement.Merge(m, src)
}
func (m *Agreement) XXX_Size() int {
	return m.Size()
}
func (m *Agreement) XXX_DiscardUnknown() {
	xxx_messageInfo_Agreement.DiscardUnknown(m)
}

var xxx_messageInfo_Agreement proto.InternalMessageInfo

func (m *Agreement) GetMeta() *AgreementMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Agreement) GetSpSignature() []byte {
	if m != nil {
		return m.SpSignature
	}
	return nil
}

func (m *Agreement) GetCreatorSignature() []byte {
	if m != nil {
		return m.CreatorSignature
	}
	return nil
}

func (m *Agreement) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Agreement) GetStatus() Agreement_AgreementStatus {
	if m != nil {
		return m.Status
	}
	return Agreement_INIT
}

type FileMetaInfo struct {
	CreatorId            string       `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	FileHash             string       `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileSize             uint64       `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ShardCount           uint64       `protobuf:"varint,4,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	Agreements           []*Agreement `protobuf:"bytes,5,rep,name=agreements,proto3" json:"agreements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FileMetaInfo) Reset()         { *m = FileMetaInfo{} }
func (m *FileMetaInfo) String() string { return proto.CompactTextString(m) }
func (*FileMetaInfo) ProtoMessage()    {}
func (*FileMetaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b47804ec1b8d60b, []int{2}
}
func (m *FileMetaInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FileMetaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FileMetaInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FileMetaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetaInfo.Merge(m, src)
}
func (m *FileMetaInfo) XXX_Size() int {
	return m.Size()
}
func (m *FileMetaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetaInfo proto.InternalMessageInfo

func (m *FileMetaInfo) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *FileMetaInfo) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *FileMetaInfo) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileMetaInfo) GetShardCount() uint64 {
	if m != nil {
		return m.ShardCount
	}
	return 0
}

func (m *FileMetaInfo) GetAgreements() []*Agreement {
	if m != nil {
		return m.Agreements
	}
	return nil
}

func init() {
	proto.RegisterEnum("filemeta.Agreement_AgreementStatus", Agreement_AgreementStatus_name, Agreement_AgreementStatus_value)
	proto.RegisterType((*AgreementMeta)(nil), "filemeta.AgreementMeta")
	proto.RegisterType((*Agreement)(nil), "filemeta.Agreement")
	proto.RegisterType((*FileMetaInfo)(nil), "filemeta.FileMetaInfo")
}

func init() { proto.RegisterFile("file_meta.proto", fileDescriptor_9b47804ec1b8d60b) }

var fileDescriptor_9b47804ec1b8d60b = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0x8e, 0x12, 0x4d,
	0x14, 0xc5, 0xa7, 0x87, 0x1e, 0x3e, 0xfa, 0x36, 0x7c, 0x83, 0x35, 0x46, 0x3b, 0x31, 0x32, 0xc8,
	0x6c, 0x88, 0x93, 0x81, 0x84, 0x59, 0xba, 0x30, 0x3a, 0x62, 0xec, 0xc4, 0x51, 0xd3, 0xb0, 0x72,
	0xd3, 0x29, 0xe8, 0x0b, 0x54, 0xa4, 0xff, 0xa4, 0xaa, 0x88, 0x66, 0x1e, 0xc3, 0x95, 0x2f, 0xe3,
	0xde, 0xa5, 0x8f, 0x60, 0xf0, 0x0d, 0x7c, 0x02, 0x53, 0xb7, 0x1a, 0x18, 0xc9, 0xec, 0xa8, 0xdf,
	0x39, 0xb7, 0x53, 0xb7, 0xce, 0x01, 0x8e, 0x67, 0x62, 0x89, 0x71, 0x8a, 0x9a, 0xf7, 0x0a, 0x99,
	0xeb, 0x9c, 0xd5, 0x0c, 0x30, 0xe7, 0xce, 0x9f, 0x43, 0x68, 0xbc, 0x98, 0x4b, 0xc4, 0x14, 0x33,
	0x7d, 0x8d, 0x9a, 0xb3, 0x27, 0x50, 0xe7, 0x1b, 0x10, 0x8b, 0x24, 0x70, 0xda, 0x4e, 0xd7, 0x8b,
	0xfc, 0x2d, 0x0b, 0x13, 0x76, 0x02, 0x47, 0xaa, 0x30, 0xda, 0x21, 0x69, 0xae, 0x2a, 0xc2, 0x84,
	0x3d, 0x06, 0x98, 0x4a, 0xe4, 0x3a, 0x97, 0x46, 0xa9, 0x90, 0xe2, 0x95, 0xc4, 0xca, 0x6a, 0xc1,
	0x65, 0x12, 0x2f, 0xb8, 0x5a, 0x04, 0xae, 0x95, 0x89, 0xbc, 0xe1, 0x6a, 0xc1, 0x4e, 0xc1, 0xb7,
	0xb2, 0xc8, 0x12, 0xfc, 0x12, 0x1c, 0xb5, 0x9d, 0xae, 0x1b, 0xd9, 0x89, 0xd0, 0x90, 0xdd, 0xbc,
	0x12, 0x37, 0x18, 0x54, 0x49, 0xb7, 0xf3, 0x23, 0x71, 0x83, 0xec, 0x3e, 0x1c, 0x15, 0x52, 0x4c,
	0x31, 0xf8, 0x8f, 0x14, 0x7b, 0x60, 0x0f, 0xa0, 0xca, 0xd3, 0x7c, 0x95, 0xe9, 0xa0, 0x46, 0xb8,
	0x3c, 0x19, 0xb7, 0xce, 0x3f, 0x61, 0x16, 0x78, 0x74, 0x0f, 0x7b, 0xa0, 0xcd, 0x57, 0x3a, 0x8f,
	0x25, 0x66, 0xf8, 0x99, 0x2f, 0x03, 0x68, 0x3b, 0xdd, 0x5a, 0xe4, 0x1b, 0x16, 0x59, 0xc4, 0xce,
	0xa0, 0xa1, 0x74, 0x2e, 0xf9, 0x1c, 0x63, 0xa5, 0xb9, 0xd4, 0x81, 0x4f, 0xdf, 0xad, 0x97, 0x70,
	0x64, 0x18, 0xed, 0x52, 0x9a, 0x30, 0x4b, 0x82, 0x7a, 0xb9, 0x8b, 0x45, 0xc3, 0x2c, 0xe9, 0x7c,
	0x3d, 0x04, 0x6f, 0xfb, 0xe8, 0xec, 0x1c, 0x5c, 0x13, 0x05, 0x3d, 0xb4, 0x3f, 0x78, 0xd8, 0xdb,
	0x64, 0xd3, 0xfb, 0x27, 0x97, 0x88, 0x4c, 0xe6, 0x8e, 0xaa, 0x88, 0x95, 0x98, 0x67, 0x5c, 0xaf,
	0x24, 0x52, 0x02, 0xf5, 0xc8, 0x57, 0xc5, 0x68, 0x83, 0xd8, 0x39, 0xdc, 0xdb, 0x04, 0xb1, 0xf3,
	0x55, 0xc8, 0xd7, 0x2c, 0x85, 0x9d, 0xf9, 0x14, 0x7c, 0x62, 0x18, 0x6b, 0x91, 0x22, 0xe5, 0xe2,
	0x46, 0x36, 0x48, 0x1c, 0x8b, 0x14, 0xd9, 0x33, 0xa8, 0x2a, 0xcd, 0xf5, 0x4a, 0x51, 0x26, 0xff,
	0x0f, 0xce, 0xee, 0xb8, 0xdf, 0xee, 0xd7, 0x88, 0xac, 0x51, 0x39, 0xd2, 0x79, 0x0a, 0xc7, 0x7b,
	0x12, 0xab, 0x81, 0x1b, 0xbe, 0x0b, 0xc7, 0xcd, 0x03, 0xd6, 0x00, 0xef, 0xea, 0xfd, 0xf5, 0x87,
	0xb7, 0xc3, 0xf1, 0xf0, 0x55, 0xd3, 0xe9, 0x7c, 0x77, 0xa0, 0xfe, 0x5a, 0x2c, 0xd1, 0x2c, 0x1b,
	0x66, 0xb3, 0x7c, 0xaf, 0x50, 0xce, 0x7e, 0xa1, 0x1e, 0x81, 0x47, 0xb5, 0xa6, 0x3e, 0xd9, 0x22,
	0x52, 0xad, 0xa9, 0x4e, 0x1b, 0x91, 0xca, 0x52, 0xa1, 0xa5, 0x48, 0xa4, 0xae, 0x6c, 0xbb, 0x36,
	0xa5, 0x6a, 0xb8, 0xb7, 0xba, 0x76, 0x45, 0xf5, 0xb8, 0x04, 0xd8, 0xd6, 0xdd, 0xec, 0x5d, 0xe9,
	0xfa, 0x83, 0x93, 0x3b, 0xf6, 0x8e, 0x6e, 0xd9, 0x5e, 0x3e, 0xff, 0xb1, 0x6e, 0x39, 0x3f, 0xd7,
	0x2d, 0xe7, 0xd7, 0xba, 0xe5, 0x7c, 0xfb, 0xdd, 0x3a, 0xf8, 0x78, 0x31, 0x17, 0x7a, 0xb1, 0x9a,
	0xf4, 0xa6, 0x79, 0xda, 0x9f, 0x08, 0xad, 0x73, 0x29, 0x31, 0xd3, 0xfd, 0x79, 0x7e, 0x31, 0xd1,
	0x33, 0xd5, 0xa7, 0xbf, 0xa2, 0xea, 0x9b, 0x4f, 0x26, 0x5c, 0xf3, 0x49, 0x95, 0xc0, 0xe5, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xc7, 0xca, 0x94, 0xae, 0x03, 0x00, 0x00,
}

func (m *AgreementMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AgreementMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AgreementMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.StorageEnd != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.StorageEnd))
		i--
		dAtA[i] = 0x60
	}
	if m.StorageStart != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.StorageStart))
		i--
		dAtA[i] = 0x58
	}
	if m.AutoRenewal {
		i--
		if m.AutoRenewal {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Amount != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x40
	}
	if m.Price != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x38
	}
	if m.ShardSize != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.ShardSize))
		i--
		dAtA[i] = 0x30
	}
	if m.ShardIndex != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.ShardIndex))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ShardHash) > 0 {
		i -= len(m.ShardHash)
		copy(dAtA[i:], m.ShardHash)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.ShardHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CreatorId) > 0 {
		i -= len(m.CreatorId)
		copy(dAtA[i:], m.CreatorId)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.CreatorId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SpId) > 0 {
		i -= len(m.SpId)
		copy(dAtA[i:], m.SpId)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.SpId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AgreementId) > 0 {
		i -= len(m.AgreementId)
		copy(dAtA[i:], m.AgreementId)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.AgreementId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Agreement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Agreement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Agreement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Status != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.CreateTime != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.CreateTime))
		i--
		dAtA[i] = 0x20
	}
	if len(m.CreatorSignature) > 0 {
		i -= len(m.CreatorSignature)
		copy(dAtA[i:], m.CreatorSignature)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.CreatorSignature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SpSignature) > 0 {
		i -= len(m.SpSignature)
		copy(dAtA[i:], m.SpSignature)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.SpSignature)))
		i--
		dAtA[i] = 0x12
	}
	if m.Meta != nil {
		{
			size, err := m.Meta.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFileMeta(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FileMetaInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileMetaInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FileMetaInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Agreements) > 0 {
		for iNdEx := len(m.Agreements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Agreements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFileMeta(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ShardCount != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.ShardCount))
		i--
		dAtA[i] = 0x20
	}
	if m.FileSize != 0 {
		i = encodeVarintFileMeta(dAtA, i, uint64(m.FileSize))
		i--
		dAtA[i] = 0x18
	}
	if len(m.FileHash) > 0 {
		i -= len(m.FileHash)
		copy(dAtA[i:], m.FileHash)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.FileHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CreatorId) > 0 {
		i -= len(m.CreatorId)
		copy(dAtA[i:], m.CreatorId)
		i = encodeVarintFileMeta(dAtA, i, uint64(len(m.CreatorId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFileMeta(dAtA []byte, offset int, v uint64) int {
	offset -= sovFileMeta(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AgreementMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AgreementId)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	l = len(m.SpId)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	l = len(m.CreatorId)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	l = len(m.ShardHash)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	if m.ShardIndex != 0 {
		n += 1 + sovFileMeta(uint64(m.ShardIndex))
	}
	if m.ShardSize != 0 {
		n += 1 + sovFileMeta(uint64(m.ShardSize))
	}
	if m.Price != 0 {
		n += 1 + sovFileMeta(uint64(m.Price))
	}
	if m.Amount != 0 {
		n += 1 + sovFileMeta(uint64(m.Amount))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	if m.AutoRenewal {
		n += 2
	}
	if m.StorageStart != 0 {
		n += 1 + sovFileMeta(uint64(m.StorageStart))
	}
	if m.StorageEnd != 0 {
		n += 1 + sovFileMeta(uint64(m.StorageEnd))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Agreement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Meta != nil {
		l = m.Meta.Size()
		n += 1 + l + sovFileMeta(uint64(l))
	}
	l = len(m.SpSignature)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	l = len(m.CreatorSignature)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	if m.CreateTime != 0 {
		n += 1 + sovFileMeta(uint64(m.CreateTime))
	}
	if m.Status != 0 {
		n += 1 + sovFileMeta(uint64(m.Status))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *FileMetaInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CreatorId)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	l = len(m.FileHash)
	if l > 0 {
		n += 1 + l + sovFileMeta(uint64(l))
	}
	if m.FileSize != 0 {
		n += 1 + sovFileMeta(uint64(m.FileSize))
	}
	if m.ShardCount != 0 {
		n += 1 + sovFileMeta(uint64(m.ShardCount))
	}
	if len(m.Agreements) > 0 {
		for _, e := range m.Agreements {
			l = e.Size()
			n += 1 + l + sovFileMeta(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovFileMeta(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFileMeta(x uint64) (n int) {
	return sovFileMeta(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AgreementMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFileMeta
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AgreementMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AgreementMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgreementId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgreementId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardIndex", wireType)
			}
			m.ShardIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardSize", wireType)
			}
			m.ShardSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoRenewal", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AutoRenewal = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageStart", wireType)
			}
			m.StorageStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageStart |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageEnd", wireType)
			}
			m.StorageEnd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageEnd |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFileMeta(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFileMeta
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Agreement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFileMeta
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Agreement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Agreement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Meta == nil {
				m.Meta = &AgreementMeta{}
			}
			if err := m.Meta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpSignature = append(m.SpSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.SpSignature == nil {
				m.SpSignature = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorSignature = append(m.CreatorSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.CreatorSignature == nil {
				m.CreatorSignature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			m.CreateTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Agreement_AgreementStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFileMeta(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFileMeta
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FileMetaInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFileMeta
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileMetaInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileMetaInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
			}
			m.FileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardCount", wireType)
			}
			m.ShardCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agreements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFileMeta
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFileMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Agreements = append(m.Agreements, &Agreement{})
			if err := m.Agreements[len(m.Agreements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFileMeta(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFileMeta
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFileMeta(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFileMeta
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFileMeta
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFileMeta
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFileMeta
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFileMeta
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFileMeta        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFileMeta          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFileMeta = fmt.Errorf("proto: unexpected end of group")
)
